# Generated by Django 3.0.5 on 2020-04-19 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0004_auto_20200418_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='assig',
        ),
        migrations.AddField(
            model_name='bug',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
