# Generated by Django 3.0.5 on 2020-04-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('bugs', '0005_auto_20200419_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='redolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='tag',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
