# Generated by Django 3.0.5 on 2020-04-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20200421_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='redolved',
            new_name='resolved',
        ),
    ]
